<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dfy</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\{\s*(//.*)?$|^\s*// \{\{\{)</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\}|// \}\}\}$)</string>
	<key>name</key>
	<string>Dafny</string>
	<key>patterns</key>
	<array>
	  <dict>
			<key>begin</key>
			<string>(\bvar\b)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dafny</string>
				</dict>
			</dict>
			<key>end</key>
			<string>:=|:\||;|\)|\}|(?=(?:abstract|class|const|constructor|export|function|ghost|greatest|import|include|iterator|least|lemma|method|module|opaque|opened|predicate|refines|static|trait|twostate|var)\b)</string>
			<key>name</key>
			<string>meta.vardecl.dafny</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
			  <dict>
				  <key>include</key>
				  <string>#formalTypeDeclaration</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(class\b)\s*([\w'?]+\b(?!&lt;))?\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dafny</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.dafny</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\w'?]+)?\s*\{(?!:)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.dafny</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.identifier.dafny</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(extends)\s+([\w'?]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.dafny</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.dafny</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.class.extends.identifier</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
	  <key>formalTypeDeclaration</key>
		<dict>
			<key>name</key>
			<string>meta.type.formaldeclaration</string>
			<key>begin</key>
			<string>(?<!\{|:|(?:label|assert|requires)\s*[_\w]+):\s*(?:[\w'?]+\.)*([\w'?]+\b(?!&lt;))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.dafny</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=&lt;|\s*|,|\)|\}|(?:requires|ensures|modifies|reads|class|codatatype|const|constructor|datatype|function|greatest|iterator|least|lemma|method|module|newtype|opaque|predicate|trait|type|var)\b))</string>
		</dict>
		<key>genericfunctioncalls</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z'?][\w'?]*)\s*&lt;(?=(?:[^\)\(]|\((?:!new|,|0|00|==)*\))*&gt;(?=\())</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.dafny</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;(?=\()</string>
			<key>name</key>
			<string>meta.method.genericfunctioncall</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\w'?]+</string>
					<key>name</key>
					<string>storage.type.dafny</string>
				</dict>
			</array>
		</dict>
		<key>functioncalls</key>
		<dict>
			<key>begin</key>
			<string>([\w'?]+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.dafny</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.method.functioncall</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordsIfNotHandled</string>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#genericfunctioncalls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functioncalls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typedeclaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordsIfNotHandled</string>
				</dict>
			</array>
		</dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{:(\w+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.dafny</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>attribute</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dafny</string>
						</dict>
					</dict>
					<key>match</key>
					<string>/\*\*/</string>
					<key>name</key>
					<string>comment.block.empty.dafny</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dafny</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.dafny</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments-inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.dafny</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dafny</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*((//).*$\n?)</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>@"</string>
					<key>end</key>
					<string>"(?!")</string>
					<key>name</key>
					<string>string.multiline.dafny</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>""</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>("|\n)</string>
					<key>name</key>
					<string>string.singleline.dafny</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\((\\)|("))</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>typedeclaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(datatype|codatatype|type|newtype)(?=.*=)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.dafny</string>
						</dict>
					</dict>
					<key>end</key>
					<string>=</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#generics</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[\w'?]+</string>
							<key>name</key>
							<string>storage.type.dafny</string>
						</dict>
					</array>
					<key>name</key>
					<string>datatype.declaration</string>
				</dict>
			</array>
		</dict>
		<key>keywordsIfNotHandled</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(datatype|codatatype|type|newtype)\b</string>
					<key>name</key>
					<string>keyword.control.dafny</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(abstract|allocated|as|assert|assume|break|by|calc|case|class|const|constructor|continue|downto|else|exists|expect|export|extends|false|for|forall|fresh|function|ghost|greatest|if|import|in|include|is|iterator|label|least|lemma|match|method|modify|module|nameonly|new|null|old|opaque|opened|predicate|print|refines|return|returns|reveal|static|then|to|trait|true|twostate|unchanged|var|while|witness|yield|yields)\b</string>
					<key>name</key>
					<string>keyword.control.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(function)\b</string>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(requires|ensures|modifies|reads|invariant|decreases|reveals|provides)\b</string>
					<key>name</key>
					<string>keyword.control.verify.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bool|char|real|multiset|map|imap|nat|int|ORDINAL|object|string|set|iset|seq|array|array[1-9]\d*|bv0|bv[1-9]\d*)\b</string>
					<key>name</key>
					<string>keyword.type.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>this</string>
					<key>name</key>
					<string>storage.type.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|:</string>
					<key>name</key>
					<string>keyword.control.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(:=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.dafny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|&amp;&amp;|\|\||&lt;==&gt;|==&gt;|&lt;==)</string>
					<key>name</key>
					<string>keyword.operator.logical.dafny</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.parameters.parenthesized</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywordsIfNotHandled</string>
						</dict>
					</array>
				</dict>
				<dict>
				  <key>include</key>
					<string>#formalTypeDeclaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functioncalls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
				<!--dict> Turning it on causes performance problems, I don't know why
					<key>include</key>
					<string>$self</string>
				</dict-->
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>generics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-zA-Z][\w'?]*)&lt;(?=[\w'?]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.dafny</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>name</key>
					<string>meta.type.generic.dafny</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#generics</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[\w'?]+</string>
							<key>name</key>
							<string>storage.type.dafny</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.dfy.dafny</string>
	<key>uuid</key>
	<string>f4eb6552-5503-47cf-9d18-6388d0981235</string>
</dict>
</plist>
